name: Deploy to Firebase Hosting on merge

on:
  push:
    branches:
      - main

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
      # Checkout
      - uses: actions/checkout@v4

      # Setup Flutter
      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable

      # Install dependencies
      - name: Install dependencies
        run: flutter pub get

      # Build Flutter Web
      - name: Build Flutter Web
        run: flutter build web --release

      # Cache busting (VERY IMPORTANT)
      - name: Add Version Hash for Cache Busting
        run: |
          COMMIT_HASH=$(git rev-parse --short HEAD)
          sed -i "s|</body>|<script>window.appVersion='${COMMIT_HASH}';</script></body>|" build/web/index.html

      # Install Firebase CLI
      - name: Install Firebase CLI
        run: npm install -g firebase-tools

      # Deploy
      - name: Deploy to Firebase Hosting
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
        run: firebase deploy --only hosting --non-interactive --force